# The Poof Palace Configuration - Google Cloud Edition
# ====================================================
# This file contains non-sensitive configuration
# All API keys and secrets are loaded from environment variables

# --- Google Cloud Configuration ---
# API keys are loaded from environment variables via .env file
GOOGLE_CLOUD_PROJECT_ID: "your-gcp-project-id-here"
GOOGLE_CLOUD_LOCATION: "us-central1"  # e.g., us-central1, a common location

# --- Cloud Service Models ---
GEMINI_MODEL: "gemini-1.5-flash-latest"
IMAGEN_MODEL: "imagegeneration@006"  # A powerful and recent Imagen model

# --- Security Settings ---
ENVIRONMENT: "development"  # development, staging, production
DEBUG_MODE: true
MAX_RETRY_ATTEMPTS: 3

# --- E-commerce Configuration (non-sensitive) ---
SHOPIFY_STORE_URL: "your-store.myshopify.com"

# --- File Paths ---
LORE_BIBLE_PATH: "lore_bible.txt"
IMAGE_OUTPUT_DIR: "output/images/"
LOG_FILE_PATH: "output/logs/palace.log"

# --- AI Style Configuration (Updated for Google Cloud) ---
POSITIVE_PROMPT_STYLE_SUFFIX: "in the style of a whimsical children's storybook illustration, soft golden light, warm colors, gentle watercolor textures, masterpiece, best quality"
NEGATIVE_PROMPT: "(ugly, deformed, blurry), harsh shadows, photorealistic, watermark, text, signature"

# --- Brand Identity ---
BRAND_NAME: "The Poof Palace"
MASCOT_NAME: "Lil Poof"
INSTAGRAM_HANDLE: "@ThePoofPalace"
